export const results= [
    {
        "id": 716429,
        "title": "Pasta",
        "calories": 584,
        "carbs": "84g",
        "fat": "20g",
        "image": "https://spoonacular.com/recipeImages/716429-312x231.jpg",
        "imageType": "jpg",
        "protein": "19g",
        "price":"$4",
        "content": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
        "rating":"3.9",
    },
    {
        "id": 715538,
        "title": "Brus Pasta",
        "calories": 521,
        "carbs": "69g",
        "fat": "10g",
        "image": "https://spoonacular.com/recipeImages/715538-312x231.jpg",
        "imageType": "jpg",
        "protein": "35g",
        "price":"$4",
        "content": "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
        "rating":"3.9",
    },
    {
        "id": 632485,
        "title": "Apple Cake",
        "image": "https://spoonacular.com/recipeImages/632485-312x231.jpg",
        "link": "https://spoonacular.com/recipes/apple-cake-632485",
        "type": "HTML",
        "relevance": 10000,
        "calories": 521,
        "content": "Apple Cake might be just the dessert you are searching for...",
        "price":"$4",
        "rating":"3.9",
      },
    //   {
    //     "id": 632522,
    //     "title": "Apple Crumble",
    //     "image": "https://spoonacular.com/recipeImages/632522-312x231.jpg",
    //     "link": "https://spoonacular.com/recipes/apple-crumble-632522",
    //     "type": "HTML",
    //     "relevance": 9999,
    //     "content": "Apple Crumble might be just the dessert you are searching for...",
    //     "price":"$4",
    //     "rating":"3.9",
    //   },
    //   {
    //     "id": 428571,
    //     "title": "Pleasant Apple Wine",
    //     "image": "https://spoonacular.com/productImages/469604-312x231.jpg",
    //     "link": "https://spoonacular.com/products/pleasant-valley-apple-wine-469604",
    //     "type": "HTML",
    //     "relevance": 10000,
    //     "price":"$4",
    //     "rating":"3.9",
    //   },
    //   {
    //     "id": 428573,
    //     "title": "Vineyards Apple Wine",
    //     "image": "https://spoonacular.com/productImages/428573-312x231.jpg",
    //     "link": "https://spoonacular.com/products/nv-georgetown-vineyards-apple-wine-428573",
    //     "type": "HTML",
    //     "relevance": 9999,
    //     "price":"$4",
    //     "rating":"3.9",
    //   },
    //   {
    //     "id": 429573,
    //     "title": "Apples",
    //     "image": "https://spoonacular.com/cdn/ingredients_100x100/braeburn-apples.jpg",
    //     "link": "https://spoonacular.com/academy/apples",
    //     "type": "HTML",
    //     "relevance": 90.46,
    //     "price":"$4",
    //     "rating":"3.9",
    //   },
    //   {
    //     "id": 420573,
    //     "title": "Vinegar",
    //     "image": "https://spoonacular.com/cdn/ingredients_100x100/red-wine-vinegar.jpg",
    //     "link": "https://spoonacular.com/academy/vinegar",
    //     "type": "HTML",
    //     "relevance": 23.80,
    //     "price":"$4",
    //     "rating":"3.9",
    //   }
]